language: node_js
node_js:
  - "node"
  - "6"
addons: 
  code_climate:
    repo_token: 6a59719361f7631149e9fef444579e94f2725dfd343a90d8b90432e02428fa73

after_success:
	- npm install -g codeclimate-test-reporter
	- codeclimate-test-reporter < lcov.info
